[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[scheduled-functions]]
  name = "morning-reminder"
  schedule = "0 22 * * *"
